module.exports = {
  arrowParens: "always",
  bracketSpacing: true,
  jsxBracketSameLine: false,
  jsxSingleQuote: false,
  quoteProps: "as-needed",
  singleQuote: false,
  semi: true,
  printWidth: 140,
  useTabs: false,
  tabWidth: 2,
  trailingComma: "es5",
  experimentalTernaries: true,
  vueIndentScriptAndStyle: true,
  objectWrap: "preserve",
  plugins: [require.resolve("prettier-plugin-tailwindcss")],
  tailwindAttributes: ["className"],
};
