import { Client } from "react-native-appwrite";
import {
  APPWRITE_ENDPOINT,
  APPWRITE_PLATFORM,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_STORAGE_ID,
  APPWRITE_USERS_TABLE_ID,
  APPWRITE_FORUM_POSTS_TABLE_ID,
  APPWRITE_FORUM_POST_IMAGES_TABLE_ID,
  APPWRITE_FORUM_COMMENTS_TABLE_ID,
  APPWRITE_USER_LESSON_PROGRESS_TABLE_ID,
  APPWRITE_PLANT_CATEGORIES_TABLE_ID,
  APPWRITE_CHAPTERS_TABLE_ID,
  APPWRITE_LESSONS_TABLE_ID,
  APPWRITE_LESSON_QUESTIONS_TABLE_ID,
  APPWRITE_QUESTION_OPTIONS_TABLE_ID,
  APPWRITE_USER_DAILY_ACTIVITY_TABLE_ID,
} from "@env";

export const config = {
  endpoint: APPWRITE_ENDPOINT,
  platform: APPWRITE_PLATFORM,
  projectId: APPWRITE_PROJECT_ID,
  databaseId: APPWRITE_DATABASE_ID,
  storageId: APPWRITE_STORAGE_ID,
};

export const tableIds = {
  users: APPWRITE_USERS_TABLE_ID,
  forumPosts: APPWRITE_FORUM_POSTS_TABLE_ID,
  formPostImages: APPWRITE_FORUM_POST_IMAGES_TABLE_ID,
  forumComments: APPWRITE_FORUM_COMMENTS_TABLE_ID,
  userLessonProgress: APPWRITE_USER_LESSON_PROGRESS_TABLE_ID,
  plantCategories: APPWRITE_PLANT_CATEGORIES_TABLE_ID,
  chapters: APPWRITE_CHAPTERS_TABLE_ID,
  lessons: APPWRITE_LESSONS_TABLE_ID,
  lessonQuestions: APPWRITE_LESSON_QUESTIONS_TABLE_ID,
  questionOptions: APPWRITE_QUESTION_OPTIONS_TABLE_ID,
  userDailyActivity: APPWRITE_USER_DAILY_ACTIVITY_TABLE_ID,
};

export let client: Client = new Client();

client.setEndpoint(config.endpoint).setProject(config.projectId).setPlatform(config.platform);
